export const SWITCH_TAB_HOME = 'SWITCH_TAB_HOME';
export const SWITCH_TAB_ABOUT = 'SWITCH_TAB_ABOUT';
export const SWITCH_TAB_PROJECT = 'SWITCH_TAB_PROJECT';
export const SWITCH_TAB_BLOG = 'SWITCH_TAB_BLOG';
